name = "SymbolicTransformer"
uuid = "9295511b-303f-4566-8a7e-0c11da6792f2"
authors = ["Stephen Prior <stephen@prior.technology> and contributors"]
version = "0.1.0-DEV"

[deps]
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NNlib = "872c559c-99b0-510c-b3b7-b6c96a88d5cd"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
